[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
my_project = "DxAee2iwHG4Rs9QgCh67dyMHKGhCmmUCo9ftsUpcbTqp"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
